#!/bin/bash

# Script:                       Ops 201 Class 03 Ops Challenge Solution
# Author:                       Jasmine Garcia
# Date of latest revision:      February 20, 2023
# Purpose:                      A script that prints the login history of users on this computer.

# Main

function whereami {

    # variable to show user history 
    user=$(last)

    echo "most recent login times of $user"
}

whereami

# End